### ISSUE TITLE
output sharing and how to run accelerate config

### ISSUE THREAD

**Issue by Zvyozdo4ka** [buaavrcg/BakedAvatar#16]
could you share some of the outputs? I mean meshes

i could not run `accelerate config`, as i have this error, do you know how to resolve it?

```Traceback (most recent call last):
  File "/home/yulduz/.local/lib/python3.10/site-packages/torch/__init__.py", line 174, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/yulduz/anaconda3/envs/BakedAvatar/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcufft.so.11: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yulduz/anaconda3/envs/BakedAvatar/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/home/yulduz/anaconda3/envs/BakedAvatar/lib/python3.10/site-packages/accelerate/__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "/home/yulduz/anaconda3/envs/BakedAvatar/lib/python3.10/site-packages/accelerate/accelerator.py", line 32, in <module>
    import torch
  File "/home/yulduz/.local/lib/python3.10/site-packages/torch/__init__.py", line 234, in <module>
    _load_global_deps()
  File "/home/yulduz/.local/lib/python3.10/site-packages/torch/__init__.py", line 196, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/yulduz/anaconda3/envs/BakedAvatar/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcufft.so.11: cannot open shared object file: No such file or directory
```

**Comment by dhbloo** [comment]
Hi,

the error message you showed seems to have something to do with your Pytorch installation. Could you try it on another clean installation?

Here is an [example](https://drive.google.com/file/d/1jDHNHTQV9E_1Dxoi8cIsA0w1gBZRQJ8z/view?usp=drive_link) of the multi-layer meshes outputted after stage 2 (without being fine-tuned). It contains some 3D obj files so you can take a quick visualization of the meshes. this [pkl file](https://drive.google.com/file/d/191zo5iJgLMhYAps5_kJubx-k8Qcch0dd/view?usp=drive_link) contains all the fine-tuned mesh data after stage 3 and you can use the `code/scripts/unpack_pkl.py` script to convert it for the real-time web demo.
