### ISSUE TITLE
libcurl.so.4: undefined symbol: nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation

### ISSUE THREAD

**Issue by jerrymatjila** [buaavrcg/BakedAvatar#4]
This issue may not originate from the code base of this wonderful project. However, I'm getting an error that drives me crazy. When executing the command
```bash
accelerate launch scripts/runner.py -c config/subject1.yaml -t mesh_export
```
I get this error message
```bash
Traceback (most recent call last):
File "/deepmind/experiments/buaavrcg/bakedavatar/code/scripts/runner.py", line 315, in <module>
mesh_export(**args)
File "/deepmind/experiments/buaavrcg/bakedavatar/code/scripts/mesh_export.py", line 690, in mesh_export
train_dataset = construct_class_by_name(class_name=dataset_class,
File "/deepmind/experiments/buaavrcg/bakedavatar/code/utils/misc_util.py", line 176, in construct_class_by_name
return call_func_by_name(*args, func_name=class_name, **kwargs)
File "/deepmind/experiments/buaavrcg/bakedavatar/code/utils/misc_util.py", line 169, in call_func_by_name
func_obj = get_obj_by_name(func_name)
File "/deepmind/experiments/buaavrcg/bakedavatar/code/utils/misc_util.py", line 162, in get_obj_by_name
module, obj_name = get_module_from_obj_name(name)
File "/deepmind/experiments/buaavrcg/bakedavatar/code/utils/misc_util.py", line 133, in get_module_from_obj_name
importlib.import_module(module_name)  # may raise ImportError
File "/repo/conda/envs/bakedavatar/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/deepmind/experiments/buaavrcg/bakedavatar/code/dataset/real.py", line 6, in <module>
from utils.image_util import load_rgb_image, load_mask, load_semantic
File "/deepmind/experiments/buaavrcg/bakedavatar/code/utils/image_util.py", line 3, in <module>
import cv2
ImportError: /repo/conda/envs/bakedavatar/lib/python3.10/site-packages/../../././libcurl.so.4: undefined symbol: nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation
Traceback (most recent call last):
File "/repo/conda/envs/bakedavatar/bin/accelerate", line 10, in <module>
sys.exit(main())
File "/repo/conda/envs/bakedavatar/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
args.func(args)
File "/repo/conda/envs/bakedavatar/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1023, in launch_command
simple_launcher(args)
File "/repo/conda/envs/bakedavatar/lib/python3.10/site-packages/accelerate/commands/launch.py", line 643, in simple_launcher
raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/repo/conda/envs/bakedavatar/bin/python3.10', 'scripts/runner.py', '-c', 'config/subject1.yaml', '-t', 'mesh_export']' returned non-zero exit status 1.
```
The most notable error is this part:
```bash
ImportError: /repo/conda/envs/bakedavatar/lib/python3.10/site-packages/../../././libcurl.so.4: undefined symbol: nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation
```
Have you encountered this error and how did you solve it?

**Comment by jerrymatjila** [comment]
Wow! I managed to fix this.
```bash
micromamba remove libcurl
```
